config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  namespace :admin do
    resources :users
    resources :dishes
    resources :events
    resources :interests
    resources :tours

    root to: 'users#index'
  end
  devise_for :users
  resources :tours, only: [:index] do
    post 'add_tour', on: :collection
  end

  resources :interests, only: [:index] do
    post 'add_interest', on: :collection
  end

  resources :dishes, only: [:index]

  resources :events, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  belongs_to :event
  has_one_attached :image
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :tour
  has_many :dishes
  has_one_attached :image
end

app/models/interest.rb
# frozen_string_literal: true

class Interest < ApplicationRecord
  has_many :tours
  has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  belongs_to :interest
  has_many :events
  has_many :user_tours
  has_many :users, through: :user_tours
  has_one_attached :image
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_tours
  has_many :tours, through: :user_tours
  has_many :user_interests
  has_many :interests, through: :user_interests
end

app/models/user_interest.rb
# frozen_string_literal: true

class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/models/user_tour.rb
# frozen_string_literal: true

class UserTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    before_action :authenticate_user!

    def authenticate_admin
      # TODO: Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/dishes_controller.rb
# frozen_string_literal: true

module Admin
  class DishesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Dish.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Dish.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/interests_controller.rb
# frozen_string_literal: true

module Admin
  class InterestsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Interest.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Interest.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/tours_controller.rb
# frozen_string_literal: true

module Admin
  class ToursController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Tour.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Tour.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def after_sign_in_path_for_user(_resource)
    current_user.tours.empty? ? interests_path : tours_path(interest_id: current_user.interests.last.id)
  end

  def after_sign_in_path_for(resource)
    current_user.admin ? admin_root_path : after_sign_in_path_for_user(resource)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.where(event_id: params[:id])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    # @events = Event.where(tour_id: params[:tour_id])
    if params[:tour_id]
      @events = Event.where(tour_id: params[:tour_id])
    else params[:id]
      @events = Event.where(id: params[:id]).first.tour.events
    end
  end
end

app/controllers/interests_controller.rb
# frozen_string_literal: true

class InterestsController < ApplicationController
  def index
    @interests = Interest.all
  end

  def add_interest
    current_user.interests << Interest.where(id: params[:id]).first
    redirect_to tours_path(interest_id: params[:id])
  end
end

app/controllers/tours_controller.rb
# frozen_string_literal: true

class ToursController < ApplicationController
  def index
    if params[:interest_id]
      @tours = Tour.where(interest_id: params[:interest_id])
    elsif params[:id]
      @tours = Tour.where(id: params[:id]).first.interest.tours
    else
      @tours = Tour.all
    end
    # @tours = params[:interest_id] ? Tour.where(interest_id: params[:interest_id]) : Tour.all
  end

  def add_tour
    current_user.tours << Tour.where(id: params[:id]).first
    redirect_to events_path(tour_id: params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/interests_helper.rb
# frozen_string_literal: true

module InterestsHelper
end

app/helpers/tours_helper.rb
# frozen_string_literal: true

module ToursHelper
end

app/views/dishes/index.html.slim
.tours-header
  = image_tag('logo.png', height: '90')
  .tours-header-buttons
    .tours-header-settings-button
      = image_tag('settings-icon.png', height: '30')
      == link_to 'Settings', edit_user_registration_path
    .tours-header-logout-button
      = image_tag('logout-icon.png', height: '30')
      == link_to 'Log out', destroy_user_session_path
.tours-content.container
  = link_to 'Back', events_path(id: @dishes.first.event_id), class: 'btn btn-warning back'
  .tours-content-center
    h1 Menu
    - @dishes.each do |dish|
      .tours-content-center-tour
        .tours-content-center-tour-header
          h4 #{dish.name}
        - if dish.image.attached?
          = image_tag dish.image, width: '900', class: 'tours-content-image'
        p #{dish.description}

app/views/events/index.html.slim
.tours-header
  = image_tag('logo.png', height: '90')
  .tours-header-buttons
    .tours-header-settings-button
      = image_tag('settings-icon.png', height: '30')
      == link_to 'Settings', edit_user_registration_path
    .tours-header-logout-button
      = image_tag('logout-icon.png', height: '30')
      == link_to 'Log out', root_path
.tours-content.container
  = link_to 'Back', tours_path(id: @events.first.tour_id), class: 'btn btn-warning back'
  .tours-content-center
    h1 = @events.first.tour.name
    - @events.each do |event|
      .tours-content-center-tour
        .tours-content-center-tour-header
          .tours-content-center-tour-header-title
            h5 #{event.name}
          = link_to 'Show', dishes_path(id: event.id), class: 'btn btn-warning'
        - if event.image.attached?
          = image_tag event.image, height: '500', class: 'tours-content-image'
        p #{event.description}

app/views/interests/index.html.slim
.container
  .main-content
    .left-main-content
      = image_tag('logo.png')
      = image_tag('main.png', height: '700')
    .middle-main-content
      = image_tag('music.png')
    .right-main-content
      h3 Interview
      p Choose your interest so we can pick you up tour
      .interests-button-all
        - @interests.each do |interest|
          .interests-button
            = link_to image_tag("icon#{interest.id}.png"), add_interest_interests_path(id: interest.id), method: :post
            p #{interest.name}

app/views/tours/index.html.slim
.tours-header
  = image_tag('logo.png', height: '90')
  .tours-header-buttons
    .tours-header-settings-button
      = image_tag('settings-icon.png', height: '30')
      == link_to 'Settings', edit_user_registration_path
    .tours-header-logout-button
      = image_tag('logout-icon.png', height: '30')
      == link_to 'Log out', destroy_user_session_path
.tours-content.container
  .tours-content-center
    h1 = @tours.first.interest.name
    - @tours.each do |tour|
      .tours-content-center-tour
        .tours-content-center-tour-header
          .tours-content-center-tour-header-title
            h5 #{tour.name}
            h7 #{tour.starts_at}
          = button_to 'Join', add_tour_tours_path(id: tour.id), method: :post, class: 'btn btn-warning'
        - if tour.image.attached?
          = image_tag tour.image, height: '500', class: 'tours-content-image'
        p #{tour.description}